default:
  image: docker.io/emscripten/emsdk:latest

stages:
  - build
  - test

build:js:
  stage: build
  script:
    - ln -sf $(which python3) /usr/local/bin/python
    - make js
  artifacts:
    paths:
      - build/javascript
      - javascript/olm.js
      - javascript/olm.wasm
      - javascript/olm_legacy.js
      - javascript/index.d.ts
      - javascript/exported_functions.json

build:js-nix:
  cache:
    paths:
      - /nix/store
  image: docker.io/nixos/nix
  stage: build
  script:
    - nix --extra-experimental-features nix-command --extra-experimental-features flakes build
  artifacts:
    paths:
      - result/javascript

test:js:
  stage: test
  needs:
    - build:js
  script:
    - pushd javascript
    - npm i
    - npm run test
