# TODO: consider replacing this with a smaller image
image: docker.io/inovex/gitlab-ci-android

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - export ANDROID_HOME=${ANDORID_SDK_HOME}
  - echo "sdk.dir=${ANDROID_SDK_HOME}" > ./android/local.properties
  - echo "ndk.dir=${ANDROID_NDK_HOME}" >> ./android/local.properties
  - cp -R $ANDROID_SDK_ROOT/licenses ./android/.
  - chmod +x ./android/gradlew
  - pushd android

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - android/.gradle/

build:android:aar:
  stage: build
  script:
    - ./gradlew clean assembleRelease
  artifacts:
    expire_in: 1 weeks
    paths:
      - android/olm-sdk/build/outputs/aar/*.aar
      - android/local.properties

test:android:aar:
  stage: test
  script:
    - echo "TODO fix this?"
    # - ./gradlew test
  needs:
    - build:android:aar

publish:android:aar:
  stage: test
  script:
    - ./gradlew publish
  needs:
    - build:android:aar
    - test:android:aar
